name: CI

'on':
  push:
    
jobs:
  simple-test:
    name: Simple test with scalatest
    strategy:
      matrix:
        os:
          - ubuntu-latest
        java-version:
          - 17
        jdk-distribution:
          - adopt-hotspot
    runs-on: ${{matrix.os}}
    steps:
      - name: JDK ${{ matrix.jdk-distribution }} v${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.jdk-distribution }}
          java-version: ${{ matrix.java-version }}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodule: recursive
          fetch-dept: 0
      - name: Run test
        run: ./gradlew test
      
release:
  needs:
    - simple-test
  runs-on: ubuntu-latest
  if: >-
    !github.event.repository.fork
    && (
      github.event_name != 'pull_request'
      || github.event.pull_request.head.repo.full_name == github.repository
    )
  concurrency:
    group: release-${{ github.event.number || github.ref }}
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: adopt
        server-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        server-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
    - name: Deploy
      env:
        MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm install
        npx semantic-release
  

success:
  runs-on: ubuntu-latest
  needs:
    - simple-test
    - release
  if: >-
    always() && (
      contains(join(needs.*.result, ','), 'failure')
      || !contains(join(needs.*.result, ','), 'cancelled')
    )
  steps:
    - name: Verify that there were no failures
      run: ${{ !contains(join(needs.*.result, ','), 'failure') }}